In [18]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv('/workspaces/machine-learning-zoomcamp-homework/01-intro/car_fuel_efficiency_2026.csv')

In [20]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [21]:
pd.__version__

'3.0.6'

In [22]:
print(len(df))

10000


In [23]:
print(df['fuel_type'].nunique())

3


In [24]:
print(df.isnull().sum())

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64


In [25]:
max_fuel_efficiency_from_asia =  df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()
print(f"The maximum fuel efficiency from asia is: {max_fuel_efficiency_from_asia}")

The maximum fuel efficiency from asia is: 41.2


In [26]:
median_horsepower = df['horsepower'].median()
mode_horsepower = df['horsepower'].mode()[0]
print(median_horsepower)
print(mode_horsepower)

254.0
252.0


In [27]:
df['horsepower'].fillna(0)

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...  
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [28]:
median_horsepower = df['horsepower'].median()
print(median_horsepower)

254.0


In [29]:
df_asia_cars = df[df['origin'] == 'Asia']

In [30]:
df_asia_features = df_asia_cars[['vehicle_weight', 'model_year']]

In [31]:
print(df_asia_features)

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]


In [32]:
df_asia_7 = df_asia_features.head(7)

In [33]:
print(df_asia_7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019


In [34]:
X = df_asia_7.values

In [35]:
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]


In [36]:
XTX = X.T.dot(X)

In [37]:
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]


In [38]:
XTX_inv =  np.linalg.inv(XTX)

In [39]:
(XTX_inv)

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [40]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [41]:
w = XTX_inv.dot(X.T).dot(y)

In [42]:
print(w)

[0.13644777 0.2327492 ]


In [43]:
print (w.sum())

0.36919696904925486
